# fly.toml app configuration file generated for battle-of-the-books on 2023-04-25T10:46:34-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "battle-of-the-books"
primary_region = "bos"

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true

[checks]
  [checks.alive]
    type = "tcp"
    interval = "15s"
    timeout = "2s"
    grace_period = "5s"
